# Generated by Django 2.0.4 on 2018-04-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='interval_check',
            field=models.IntegerField(blank=True),
        ),
    ]
